#pragma once

#include <QAbstractAnimation>
#include <QAbstractButton>
#include <QAbstractEventDispatcher>
#include <QAbstractGraphicsShapeItem>
#include <QAbstractItemDelegate>
#include <QAbstractItemModel>
#include <QAbstractItemView>
#include <QAbstractListModel>
#include <QAbstractNativeEventFilter>
#include <QAbstractProxyModel>
#include <QAbstractScrollArea>
#include <QAbstractSlider>
#include <QAbstractSpinBox>
#include <QAbstractState>
#include <QAbstractTableModel>
#include <QAbstractTextDocumentLayout>
#include <QAbstractTransition>
#include <QAbstractUndoItem>
#include <QAccessible>
#include <QAccessibleActionInterface>
#include <QAccessibleApplication>
#include <QAccessibleBridge>
#include <QAccessibleBridgePlugin>
#include <QAccessibleEditableTextInterface>
#include <QAccessibleEvent>
#include <QAccessibleImageInterface>
#include <QAccessibleInterface>
#include <QAccessibleObject>
#include <QAccessiblePlugin>
#include <QAccessibleStateChangeEvent>
#include <QAccessibleTableCellInterface>
#include <QAccessibleTableInterface>
#include <QAccessibleTableModelChangeEvent>
#include <QAccessibleTextCursorEvent>
#include <QAccessibleTextInsertEvent>
#include <QAccessibleTextInterface>
#include <QAccessibleTextRemoveEvent>
#include <QAccessibleTextSelectionEvent>
#include <QAccessibleTextUpdateEvent>
#include <QAccessibleValueChangeEvent>
#include <QAccessibleValueInterface>
#include <QAccessibleWidget>
#include <QAction>
#include <QActionEvent>
#include <QActionGroup>
#include <QAnimationDriver>
#include <QAnimationGroup>
#include <QApplication>
#include <QApplicationStateChangeEvent>
#include <QArgument>
#include <QArrayData>
#include <QArrayDataPointer>
#include <QArrayDataPointerRef>
#include <QAssociativeIterable>
#include <QAtomicInt>
#include <QAtomicInteger>
#include <QAtomicPointer>