#pragma once

#include <QCache>
#include <QCalendar>
#include <QCalendarWidget>
#include <QCborArray>
#include <QCborError>
#include <QCborMap>
#include <QCborParserError>
#include <QCborStreamReader>
#include <QCborStreamWriter>
#include <QCborValue>
#include <QCborValueRef>
#include <QChar>
#include <QCharRef>
#include <QCheckBox>
#include <QChildEvent>
#include <QClipboard>
#include <QCloseEvent>
#include <QCollator>
#include <QCollatorSortKey>
#include <QColor>
#include <QColorDialog>
#include <QColormap>
#include <QColorSpace>
#include <QColorTransform>
#include <QColumnView>
#include <QComboBox>
#include <QCommandLineOption>
#include <QCommandLineParser>
#include <QCommandLinkButton>
#include <QCommonStyle>
#include <QCompleter>
#include <QConcatenateTablesProxyModel>
#include <QConicalGradient>
#include <QConstOverload>
#include <QContextMenuEvent>
#include <QContiguousCache>
#include <QContiguousCacheData>
#include <QContiguousCacheTypedData>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QCursor>