#pragma once

#include <QFactoryInterface>
#include <QFile>
#include <QFileDevice>
#include <QFileDialog>
#include <QFileIconProvider>
#include <QFileInfo>
#include <QFileInfoList>
#include <QFileOpenEvent>
#include <QFileSelector>
#include <QFileSystemModel>
#include <QFileSystemWatcher>
#include <QFinalState>
#include <QFlag>
#include <QFlags>
#include <QFloat16>
#include <QFocusEvent>
#include <QFocusFrame>
#include <QFont>
#include <QFontComboBox>
#include <QFontDatabase>
#include <QFontDialog>
#include <QFontInfo>
#include <QFontMetrics>
#include <QFontMetricsF>
#include <QFormLayout>
#include <QFrame>
#include <QFunctionPointer>
#include <QFuture>
#include <QFutureInterface>
#include <QFutureInterfaceBase>
#include <QFutureInterfaceBase>
#include <QFutureIterator>
#include <QFutureSynchronizer>
#include <QFutureWatcher>
#include <QFutureWatcherBase>