#pragma once

#include <QIcon>
#include <QIconDragEvent>
#include <QIconEngine>
#include <QIconEnginePlugin>
#include <QIconEngineV2>
#include <QIdentityProxyModel>
#include <QImage>
#include <QImageCleanupFunction>
#include <QImageIOHandler>
#include <QImageIOPlugin>
#include <QImageReader>
#include <QImageTextKeyLang>
#include <QImageWriter>
#include <QIncompatibleFlag>
#include <QInputDialog>
#include <QInputEvent>
#include <QInputMethod>
#include <QInputMethodEvent>
#include <QInputMethodQueryEvent>
#include <QIntegerForSize>
#include <QInternal>
#include <QIntValidator>
#include <QIODevice>
#include <QItemDelegate>
#include <QItemEditorCreator>
#include <QItemEditorCreatorBase>
#include <QItemEditorFactory>
#include <QItemSelection>
#include <QItemSelectionModel>
#include <QItemSelectionRange>