#pragma once


#include <QPagedPaintDevice>
#include <QPageLayout>
#include <QPageSize>
#include <QPaintDevice>
#include <QPaintDeviceWindow>
#include <QPaintEngine>
#include <QPaintEngineState>
#include <QPainter>
#include <QPainterPath>
#include <QPainterPathStroker>
#include <QPaintEvent>
#include <QPair>
#include <QPalette>
#include <QPanGesture>
#include <QParallelAnimationGroup>
#include <QPauseAnimation>
#include <QPdfWriter>
#include <QPen>
#include <QPersistentModelIndex>
#include <QPicture>
#include <QPictureFormatPlugin>
#include <QPictureIO>
#include <QPinchGesture>
#include <QPixelFormat>
#include <QPixmap>
#include <QPixmapCache>
#include <QPlainTextDocumentLayout>
#include <QPlainTextEdit>
#include <QPlatformSurfaceEvent>
#include <QPluginLoader>
#include <QPluginMetaData>
#include <QPoint>
#include <QPointer>
#include <QPointF>
#include <QPointingDeviceUniqueId>
#include <QPolygon>
#include <QPolygonF>
#include <QProcess>
#include <QProcessEnvironment>
#include <QProgressBar>
#include <QProgressDialog>
#include <QPropertyAnimation>
#include <QProxyStyle>
#include <QPushButton>