#pragma once

#include <QSaveFile>
#include <QScopedArrayPointer>
#include <QScopedPointer>
#include <QScopedPointerArrayDeleter>
#include <QScopedPointerDeleteLater>
#include <QScopedPointerDeleter>
#include <QScopedPointerObjectDeleteLater>
#include <QScopedPointerPodDeleter>
#include <QScopedValueRollback>
#include <QScopeGuard>
#include <QScreen>
#include <QScreenOrientationChangeEvent>
#include <QScrollArea>
#include <QScrollBar>
#include <QScroller>
#include <QScrollerProperties>
#include <QScrollEvent>
#include <QScrollPrepareEvent>
#include <QSemaphore>
#include <QSemaphoreReleaser>
#include <QSequentialAnimationGroup>
#include <QSequentialIterable>
#include <QSessionManager>
#include <QSet>
#include <QSetIterator>
#include <QSettings>
#include <QSharedData>
#include <QSharedDataPointer>
#include <QSharedMemory>
#include <QSharedPointer>
#include <QShortcut>
#include <QShortcutEvent>
#include <QShowEvent>
#include <QSignalBlocker>
#include <QSignalMapper>
#include <QSignalTransition>
#include <QSize>
#include <QSizeF>
#include <QSizeGrip>
#include <QSizePolicy>
#include <QSlider>
#include <QSocketNotifier>
#include <QSortFilterProxyModel>
#include <QSpacerItem>
#include <QSpecialInteger>
#include <QSpinBox>
#include <QSplashScreen>
#include <QSplitter>
#include <QSplitterHandle>
#include <QStack>
#include <QStackedLayout>
#include <QStackedWidget>
#include <QStandardItem>
#include <QStandardItemEditorCreator>
#include <QStandardItemModel>
#include <QStandardPaths>
#include <QState>
#include <QStateMachine>
#include <QStaticArrayData>
#include <QStaticByteArrayData>
#include <QStaticByteArrayMatcherBase>
#include <QStaticPlugin>
#include <QStaticStringData>
#include <QStaticText>
#include <QStatusBar>
#include <QStatusTipEvent>
#include <QStorageInfo>
#include <QString>
#include <QStringAlgorithms>
#include <QStringBuilder>
#include <QStringData>
#include <QStringDataPtr>
#include <QStringList>
#include <QStringListIterator>
#include <QStringListModel>
#include <QStringLiteral>
#include <QStringMatcher>
#include <QStringRef>
#include <QStringView>
#include <QStyle>
#include <QStyledItemDelegate>
#include <QStyleFactory>
#include <QStyleHintReturn>
#include <QStyleHintReturnMask>
#include <QStyleHintReturnVariant>
#include <QStyleHints>
#include <QStyleOption>
#include <QStyleOptionButton>
#include <QStyleOptionComboBox>
#include <QStyleOptionComplex>
#include <QStyleOptionDockWidget>
#include <QStyleOptionDockWidgetV2>
#include <QStyleOptionFocusRect>
#include <QStyleOptionFrame>
#include <QStyleOptionFrameV2>
#include <QStyleOptionFrameV3>
#include <QStyleOptionGraphicsItem>
#include <QStyleOptionGroupBox>
#include <QStyleOptionHeader>
#include <QStyleOptionMenuItem>
#include <QStyleOptionProgressBar>
#include <QStyleOptionProgressBarV2>
#include <QStyleOptionRubberBand>
#include <QStyleOptionSizeGrip>
#include <QStyleOptionSlider>
#include <QStyleOptionSpinBox>
#include <QStyleOptionTab>
#include <QStyleOptionTabBarBase>
#include <QStyleOptionTabBarBaseV2>
#include <QStyleOptionTabV2>
#include <QStyleOptionTabV3>
#include <QStyleOptionTabWidgetFrame>
#include <QStyleOptionTabWidgetFrameV2>
#include <QStyleOptionTitleBar>
#include <QStyleOptionToolBar>
#include <QStyleOptionToolBox>
#include <QStyleOptionToolBoxV2>
#include <QStyleOptionToolButton>
#include <QStyleOptionViewItem>
#include <QStyleOptionViewItemV2>
#include <QStyleOptionViewItemV3>
#include <QStyleOptionViewItemV4>
#include <QStylePainter>
#include <QStylePlugin>
#include <QSurface>
#include <QSurfaceFormat>
#include <QSwipeGesture>
#include <QSyntaxHighlighter>
#include <QSysInfo>
#include <QSystemSemaphore>
#include <QSystemTrayIcon>