#pragma once

#include <QTabBar>
#include <QTabletEvent>
#include <QTableView>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QTableWidgetSelectionRange>
#include <QTabWidget>
#include <QTapAndHoldGesture>
#include <QTapGesture>
#include <QTemporaryDir>
#include <QTemporaryFile>
#include <QTextBlock>
#include <QTextBlockFormat>
#include <QTextBlockGroup>
#include <QTextBlockUserData>
#include <QTextBoundaryFinder>
#include <QTextBrowser>
#include <QTextCharFormat>
#include <QTextCodec>
#include <QTextCursor>
#include <QTextDecoder>
#include <QTextDocument>
#include <QTextDocumentFragment>
#include <QTextDocumentWriter>
#include <QTextEdit>
#include <QTextEncoder>
#include <QTextFormat>
#include <QTextFragment>
#include <QTextFrame>
#include <QTextFrameFormat>
#include <QTextFrameLayoutData>
#include <QTextImageFormat>
#include <QTextInlineObject>
#include <QTextItem>
#include <QTextLayout>
#include <QTextLength>
#include <QTextLine>
#include <QTextList>
#include <QTextListFormat>
#include <QTextObject>
#include <QTextObjectInterface>
#include <QTextOption>
#include <QTextStream>
#include <QTextStreamFunction>
#include <QTextStreamManipulator>
#include <QTextTable>
#include <QTextTableCell>
#include <QTextTableCellFormat>
#include <QTextTableFormat>
#include <QThread>
#include <QThreadPool>
#include <QThreadStorage>
#include <QThreadStorageData>
#include <QTileRules>
#include <QTime>
#include <QTimeEdit>
#include <QTimeLine>
#include <QTimer>
#include <QTimerEvent>
#include <QTimeZone>
#include <QToolBar>
#include <QToolBarChangeEvent>
#include <QToolBox>
#include <QToolButton>
#include <QToolTip>
#include <QTouchDevice>
#include <QTouchEvent>
#include <QTransform>
#include <QTranslator>
#include <QTransposeProxyModel>
#include <QTreeView>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QTreeWidgetItemIterator>
#include <QTypeInfo>
#include <QTypeInfoMerger>
#include <QTypeInfoQuery>