#pragma once

#include <QWaitCondition>
#include <QWeakPointer>
#include <QWhatsThis>
#include <QWhatsThisClickedEvent>
#include <QWheelEvent>
#include <QWidget>
#include <QWidgetAction>
#include <QWidgetData>
#include <QWidgetItem>
#include <QWidgetItemV2>
#include <QWidgetList>
#include <QWidgetMapper>
#include <QWidgetSet>
#include <QWindow>
#include <QWindowList>
#include <QWindowStateChangeEvent>
#include <QWinEventNotifier>
#include <QWizard>
#include <QWizardPage>
#include <QWriteLocker>